
import { Question } from './types';

export const QUESTION_BANK: Question[] = [
  // --- 数学基础题 (category: basic) ---
  { id: 'm-b-1', category: 'basic', type: 'multiple-choice', text: '列竖式计算：368 + 235 =', options: ['603', '593', '613'], answer: '603', explanation: '个位8+5=13进1，十位6+3+1=10进1，百位3+2+1=6。' },
  { id: 'm-b-2', category: 'basic', type: 'multiple-choice', text: '计算：9 + 4 + 6 + 11 =', options: ['30', '29', '31'], answer: '30', explanation: '巧算：(9+11) + (4+6) = 20 + 10 = 30。' },
  { id: 'm-b-3', category: 'basic', type: 'multiple-choice', text: '计算：37 - 8 - 12 =', options: ['17', '19', '15'], answer: '17', explanation: '巧算：37 - (8+12) = 37 - 20 = 17。' },
  { id: 'm-b-4', category: 'basic', type: 'multiple-choice', text: '在方框中填数使算式成立：3□ + □8 = 72', options: ['34+38', '33+39', '35+37'], answer: '34+38', explanation: '个位4+8=12进1，十位3+3+1=7。' },
  { id: 'm-b-5', category: 'basic', type: 'multiple-choice', text: '在（ ）中填入符号使等式成立：8 ( ) 3 ( ) 5 = 6', options: ['- , +', '+ , -', '- , -'], answer: '+ , -', explanation: '8 + 3 = 11, 11 - 5 = 6。所以应填 + 和 -。' },
  { id: 'm-b-6', category: 'basic', type: 'multiple-choice', text: '用2, 5, 7, 10填空使等式成立：( ) + ( ) - ( ) = ( )', options: ['2 + 10 - 5 = 7', '2 + 5 - 7 = 0', '10 + 7 - 5 = 12'], answer: '2 + 10 - 5 = 7', explanation: '2+10=12, 12-5=7。四个数都用到了！' },
  { id: 'm-b-7', category: 'basic', type: 'multiple-choice', text: '哪些是奇数？ ①17 ②24 ③39 ④50 ⑤83', options: ['①③⑤', '①②③', '③④⑤'], answer: '①③⑤', explanation: '不能被2整除的数是奇数，看个位是1,3,5,7,9。' },
  { id: 'm-b-8', category: 'basic', type: 'multiple-choice', text: '1个菠萝=4个苹果，1个苹果=3个橘子，1个菠萝等于几个橘子？', options: ['12个', '7个', '8个'], answer: '12个', explanation: '4个苹果就是4个3，4 × 3 = 12。' },
  { id: 'm-b-9', category: 'basic', type: 'multiple-choice', text: '小明7岁，爸爸35岁，5年后爸爸比小明大几岁？', options: ['28岁', '33岁', '40岁'], answer: '28岁', explanation: '年龄差永远不变：35 - 7 = 28。' },
  { id: 'm-b-10', category: 'basic', type: 'multiple-choice', text: '一根绳子长12米，对折以后再对折，每折长多少米？', options: ['3米', '6米', '4米'], answer: '3米', explanation: '对折一次是6米，再对折就是3米。' },
  { id: 'm-b-11', category: 'basic', type: 'multiple-choice', text: '3元6角 = （ ）角', options: ['36', '306', '63'], answer: '36', explanation: '1元=10角，3元=30角，30+6=36角。' },
  { id: 'm-b-12', category: 'basic', type: 'multiple-choice', text: '钟面上，分针指向6，时针在3和4之间，现在是（ ）', options: ['3时半', '3时6分', '4时半'], answer: '3时半', explanation: '分针指6表示30分（半），时针走过3不到4，所以是3时30分（3时半）。' },
  { id: 'm-b-13', category: 'basic', type: 'multiple-choice', text: '把 37、89、56、23 按从大到小的顺序排列，排在第二位的是：', options: ['56', '37', '89'], answer: '56', explanation: '89 > 56 > 37 > 23。第二大的是56。' },
  { id: 'm-b-14', category: 'basic', type: 'multiple-choice', text: '50角 = （ ）元', options: ['5', '50', '500'], answer: '5', explanation: '10角=1元，50角里面有5个10，所以是5元。' },
  { id: 'm-b-15', category: 'basic', type: 'multiple-choice', text: '找规律填数：3、6、9、（ ）、15', options: ['12', '11', '13'], answer: '12', explanation: '每次加3。9+3=12。' },
// --- 数学基础题 (category: basic) ---
{ id: 'm-b-16', category: 'basic', type: 'multiple-choice', text: '列竖式计算：512 - 189 =', options: ['323', '423', '333'], answer: '323', explanation: '个位2借1成12-9=3，十位0借1成10-8=2，百位4-1=3。' },
{ id: 'm-b-17', category: 'basic', type: 'multiple-choice', text: '计算：25 + 17 + 75 =', options: ['117', '107', '127'], answer: '117', explanation: '巧算：(25+75)+17=100+17=117。' },
{ id: 'm-b-18', category: 'basic', type: 'multiple-choice', text: '7千米 = （ ）米', options: ['7000', '700', '70'], answer: '7000', explanation: '1千米=1000米，7×1000=7000米。' },
{ id: 'm-b-19', category: 'basic', type: 'multiple-choice', text: '找规律填数：2、4、8、16、（ ）', options: ['32', '24', '30'], answer: '32', explanation: '后一个数是前一个数的2倍，16×2=32。' },
{ id: 'm-b-20', category: 'basic', type: 'multiple-choice', text: '一个正方形的边长是5厘米，它的周长是多少？', options: ['20厘米', '25厘米', '10厘米'], answer: '20厘米', explanation: '正方形周长=边长×4，5×4=20厘米。' },
{ id: 'm-b-21', category: 'basic', type: 'multiple-choice', text: '计算：99 - 23 - 37 =', options: ['39', '49', '59'], answer: '39', explanation: '巧算：99-(23+37)=99-60=39。' },
{ id: 'm-b-22', category: 'basic', type: 'multiple-choice', text: '钟面上时针走一大格，分针走多少小格？', options: ['60', '12', '5'], answer: '60', explanation: '时针走1大格是1小时，1小时分针走1圈即60小格。' },
{ id: 'm-b-23', category: 'basic', type: 'multiple-choice', text: '哪些是偶数？①22 ②35 ③48 ④61 ⑤70', options: ['①③⑤', '②④', '①②③'], answer: '①③⑤', explanation: '能被2整除的数是偶数，个位是0、2、4、6、8。' },
{ id: 'm-b-24', category: 'basic', type: 'multiple-choice', text: '8吨 = （ ）千克', options: ['8000', '800', '80'], answer: '8000', explanation: '1吨=1000千克，8×1000=8000千克。' },
{ id: 'm-b-25', category: 'basic', type: 'multiple-choice', text: '在方框填数：6□5 - □2 = 623', options: ['645-22', '655-32', '635-12'], answer: '655-32', explanation: '个位5-2=3，十位5-3=2，百位6不变，即655-32=623。' },
{ id: 'm-b-26', category: 'basic', type: 'multiple-choice', text: '长方形长9厘米，宽4厘米，周长是多少？', options: ['26厘米', '36厘米', '13厘米'], answer: '26厘米', explanation: '长方形周长=(长+宽)×2，(9+4)×2=26厘米。' },
{ id: 'm-b-27', category: 'basic', type: 'multiple-choice', text: '4元8角5分 = （ ）分', options: ['485', '4085', '4805'], answer: '485', explanation: '4元=400分，8角=80分，400+80+5=485分。' },
{ id: 'm-b-28', category: 'basic', type: 'multiple-choice', text: '找规律填数：1、4、9、16、（ ）', options: ['25', '24', '20'], answer: '25', explanation: '依次是1×1、2×2、3×3、4×4，下一个是5×5=25。' },
{ id: 'm-b-29', category: 'basic', type: 'multiple-choice', text: '计算：125 + 369 + 75 =', options: ['569', '469', '579'], answer: '569', explanation: '巧算：(125+75)+369=200+369=569。' },
{ id: 'm-b-30', category: 'basic', type: 'multiple-choice', text: '钟面上分针走一小格，秒针走多少小格？', options: ['60', '12', '1'], answer: '60', explanation: '分针走1小格是1分钟，1分钟秒针走1圈即60小格。' },
{ id: 'm-b-31', category: 'basic', type: 'multiple-choice', text: '1个西瓜=2个哈密瓜，1个哈密瓜=6个桃子，1个西瓜=几个桃子？', options: ['12', '8', '6'], answer: '12', explanation: '2个哈密瓜就是2×6=12个桃子。' },
{ id: 'm-b-32', category: 'basic', type: 'multiple-choice', text: '把 456、389、502、498 按从小到大排，排在第三位的是：', options: ['498', '456', '502'], answer: '498', explanation: '389 < 456 < 498 < 502，第三位是498。' },
{ id: 'm-b-33', category: 'basic', type: 'multiple-choice', text: '列竖式计算：386 + 457 - 298 =', options: ['545', '445', '645'], answer: '545', explanation: '先算386+457=843，再算843-298=545。' },
{ id: 'm-b-34', category: 'basic', type: 'multiple-choice', text: '6000克 = （ ）千克', options: ['6', '60', '600'], answer: '6', explanation: '1000克=1千克，6000里有6个1000，即6千克。' },
{ id: 'm-b-35', category: 'basic', type: 'multiple-choice', text: '在（）填符号：9（）3（）6 = 33', options: ['× , +', '+ , ×', '- , ×'], answer: '× , +', explanation: '9×3=27，27+6=33，所以填×和+。' },
{ id: 'm-b-36', category: 'basic', type: 'multiple-choice', text: '小红今年9岁，妈妈今年36岁，今年妈妈年龄是小红的几倍？', options: ['4', '3', '5'], answer: '4', explanation: '求几倍用除法，36÷9=4。' },
{ id: 'm-b-37', category: 'basic', type: 'multiple-choice', text: '找规律填数：5、10、15、（）、25、30', options: ['20', '18', '22'], answer: '20', explanation: '每次加5，15+5=20。' },
{ id: 'm-b-38', category: 'basic', type: 'multiple-choice', text: '一个三位数，百位是5，十位是0，个位是8，这个数是？', options: ['508', '580', '805'], answer: '508', explanation: '百位5表示500，个位8表示8，合起来是508。' },
{ id: 'm-b-39', category: 'basic', type: 'multiple-choice', text: '计算：87 - (27 + 35) =', options: ['25', '35', '45'], answer: '25', explanation: '先算括号里27+35=62，再算87-62=25。' },
{ id: 'm-b-40', category: 'basic', type: 'multiple-choice', text: '钟面上3时整，时针和分针形成的角是什么角？', options: ['直角', '锐角', '钝角'], answer: '直角', explanation: '3时整，时针指3、分针指12，夹角是90°，为直角。' },
{ id: 'm-b-41', category: 'basic', type: 'multiple-choice', text: '用3、6、9组成最大的三位数是？', options: ['963', '936', '693'], answer: '963', explanation: '把数字从大到小排列，百位9、十位6、个位3，即963。' },
{ id: 'm-b-42', category: 'basic', type: 'multiple-choice', text: '2米3分米 = （ ）分米', options: ['23', '203', '32'], answer: '23', explanation: '2米=20分米，20+3=23分米。' },
{ id: 'm-b-43', category: 'basic', type: 'multiple-choice', text: '用1、0、5组成最小的三位数是？', options: ['105', '150', '501'], answer: '105', explanation: '0不能在百位，百位1、十位0、个位5，即105。' },
{ id: 'm-b-44', category: 'basic', type: 'multiple-choice', text: '计算：45 × 2 × 5 =', options: ['450', '90', '45'], answer: '450', explanation: '巧算：45×(2×5)=45×10=450。' },
{ id: 'm-b-45', category: 'basic', type: 'multiple-choice', text: '1小时20分 = （ ）分', options: ['80', '60', '120'], answer: '80', explanation: '1小时=60分，60+20=80分。' },
  // --- 数学应用题 (category: application) ---
  { id: 'm-a-1', category: 'application', type: 'multiple-choice', text: '超市有18箱牛奶，卖出9箱又进货12箱，现在有几箱？', options: ['21箱', '15箱', '30箱'], answer: '21箱', explanation: '18 - 9 = 9, 9 + 12 = 21。' },
  { id: 'm-a-2', category: 'application', type: 'multiple-choice', text: '排队时，小红前面有6人，后面有8人，这一队共几人？', options: ['15人', '14人', '13人'], answer: '15人', explanation: '前面6人 + 小红1人 + 后面8人 = 15人。' },
  { id: 'm-a-3', category: 'application', type: 'multiple-choice', text: '妈妈买25个苹果，剩7个，分给家人几个？', options: ['18个', '32个', '12个'], answer: '18个', explanation: '25 - 7 = 18。' },
  { id: 'm-a-4', category: 'application', type: 'multiple-choice', text: '篮子A有16个蛋，篮子B有10个，怎样移动能相等？', options: ['A给B 3个', 'A给B 6个', 'B给A 3个'], answer: 'A给B 3个', explanation: '总数26，每篮应13个。16-13=3。' },
  { id: 'm-a-5', category: 'application', type: 'multiple-choice', text: '木头锯成4段要锯几次？每锯一次3分钟共几分钟？', options: ['3次，9分钟', '4次，12分钟', '3次，6分钟'], answer: '3次，9分钟', explanation: '锯4段只需锯3次，3 × 3 = 9。' },
  { id: 'm-a-6', category: 'application', type: 'multiple-choice', text: '体育室有45只球，第一次借走9只，第二次借走10只，体育室的球比原来少了几只？', options: ['19只', '26只', '45只'], answer: '19只', explanation: '问“少了”多少，就是问“借走”了多少。9 + 10 = 19只。' },
  { id: 'm-a-7', category: 'application', type: 'multiple-choice', text: '书70页，第一天看18页，第二天看10页，第三天从第几页看起？', options: ['28页', '29页', '30页'], answer: '29页', explanation: '前两天共看了 18 + 10 = 28页。所以第三天从第 29 页开始看。' },
  { id: 'm-a-8', category: 'application', type: 'multiple-choice', text: '妈妈买了一些苹果，爸爸吃2个，爷爷、奶奶和我各吃1个，正好吃了一半。妈妈买了几个？', options: ['5个', '10个', '8个'], answer: '10个', explanation: '吃掉的数量是 2+1+1+1=5个，这正好是一半，所以原来有 5+5=10个。' },
  { id: 'm-a-9', category: 'application', type: 'multiple-choice', text: '家里有2只白兔，每只白兔生了3只小兔，现在一共有几只兔子？', options: ['6只', '8只', '5只'], answer: '8只', explanation: '大兔子2只，小兔子 2 × 3 = 6只。总共 2 + 6 = 8只。' },
  { id: 'm-a-10', category: 'application', type: 'multiple-choice', text: '排队体检，从前面数乐乐是第12个，从后面数乐乐是第9个，这一队一共有多少人？', options: ['20人', '21人', '12人'], answer: '20人', explanation: '乐乐被数了两次，所以要减1。12 + 9 - 1 = 20人。' },
  { id: 'm-a-11', category: 'application', type: 'multiple-choice', text: '小明带50元买文具，买书包花36元，买文具盒花8元，还剩多少钱？', options: ['6元', '14元', '42元'], answer: '6元', explanation: '50 - 36 - 8 = 6元。或者 50 - (36+8) = 6元。' },
  { id: 'm-a-12', category: 'application', type: 'multiple-choice', text: '一根绳子剪3次，能剪成几段？', options: ['3段', '4段', '2段'], answer: '4段', explanation: '段数总是比剪的次数多1。3 + 1 = 4段。' },
// --- 数学应用题 (category: application) ---
{ id: 'm-a-13', category: 'application', type: 'multiple-choice', text: '一本练习本4元，买5本送1本，买6本一共花多少钱？', options: ['20元', '24元', '16元'], answer: '20元', explanation: '买5本送1本刚好6本，只需算5本的钱：4×5=20。' },
{ id: 'm-a-14', category: 'application', type: 'multiple-choice', text: '一个长方形花坛长8米，宽5米，绕花坛走一圈是多少米？', options: ['26米', '40米', '13米'], answer: '26米', explanation: '长方形周长=(长+宽)×2，(8+5)×2=26。' },
{ id: 'm-a-15', category: 'application', type: 'multiple-choice', text: '有42块糖，平均分给7个小朋友，每个小朋友分几块？', options: ['6块', '7块', '5块'], answer: '6块', explanation: '平均分用除法，42÷7=6。' },
{ id: 'm-a-16', category: 'application', type: 'multiple-choice', text: '小明今年8岁，爸爸的年龄是他的4倍，爸爸今年多少岁？', options: ['32岁', '36岁', '24岁'], answer: '32岁', explanation: '求一个数的几倍用乘法，8×4=32。' },
{ id: 'm-a-17', category: 'application', type: 'multiple-choice', text: '商店运来4箱梨，每箱9个，卖出20个，还剩多少个梨？', options: ['16个', '36个', '56个'], answer: '16个', explanation: '先算总数4×9=36，再减卖出的，36-20=16。' },
{ id: 'm-a-18', category: 'application', type: 'multiple-choice', text: '一节课40分钟，上午8:10上课，这节课几点下课？', options: ['8:50', '9:00', '8:40'], answer: '8:50', explanation: '8时10分+40分=8时50分。' },
{ id: 'm-a-19', category: 'application', type: 'multiple-choice', text: '有30个苹果，每8个装一袋，能装满几袋？还剩几个？', options: ['3袋剩6个', '4袋剩2个', '3袋剩2个'], answer: '3袋剩6个', explanation: '有余数除法，30÷8=3……6，商是袋数，余数是剩的个数。' },
{ id: 'm-a-20', category: 'application', type: 'multiple-choice', text: '一支钢笔12元，一支圆珠笔3元，钢笔的价钱是圆珠笔的几倍？', options: ['4倍', '3倍', '5倍'], answer: '4倍', explanation: '求一个数是另一个数的几倍用除法，12÷3=4。' },
{ id: 'm-a-21', category: 'application', type: 'multiple-choice', text: '妈妈带100元，买大米花45元，买食用油花38元，还剩多少元？', options: ['17元', '27元', '83元'], answer: '17元', explanation: '100-45-38=17，或100-(45+38)=17。' },
{ id: 'm-a-22', category: 'application', type: 'multiple-choice', text: '同学们栽树，每行栽6棵，栽了5行，还剩4棵没栽，一共要栽多少棵？', options: ['34棵', '30棵', '26棵'], answer: '34棵', explanation: '先算栽好的6×5=30，再加没栽的，30+4=34。' },
{ id: 'm-a-23', category: 'application', type: 'multiple-choice', text: '一个书包35元，付50元买一个，应找回多少钱？', options: ['15元', '25元', '85元'], answer: '15元', explanation: '付出的钱-商品价钱=找回的钱，50-35=15。' },
{ id: 'm-a-24', category: 'application', type: 'multiple-choice', text: '把24块饼干分给小朋友，每人分3块，能分给几个小朋友？', options: ['8个', '7个', '9个'], answer: '8个', explanation: '包含除，24里面有几个3，24÷3=8。' },
{ id: 'm-a-25', category: 'application', type: 'multiple-choice', text: '学校图书馆有故事书65本，科技书比故事书少18本，科技书有多少本？', options: ['47本', '83本', '57本'], answer: '47本', explanation: '求比一个数少几的数用减法，65-18=47。' },
{ id: 'm-a-26', category: 'application', type: 'multiple-choice', text: '工人叔叔修马路，每天修9米，修了6天，还剩15米没修，马路总长多少米？', options: ['69米', '54米', '49米'], answer: '69米', explanation: '已修的9×6=54，加未修的，54+15=69。' },
{ id: 'm-a-27', category: 'application', type: 'multiple-choice', text: '一张成人票8元，儿童票4元，买3张成人票和1张儿童票共花多少元？', options: ['28元', '36元', '24元'], answer: '28元', explanation: '3张成人票3×8=24，加1张儿童票，24+4=28。' },
{ id: 'm-a-28', category: 'application', type: 'multiple-choice', text: '果园里有桃树27棵，梨树的棵数是桃树的3倍，梨树有多少棵？', options: ['81棵', '9棵', '30棵'], answer: '81棵', explanation: '求几倍用乘法，27×3=81。' },
{ id: 'm-a-29', category: 'application', type: 'multiple-choice', text: '有56本课外书，分给8个小组，每个小组分7本，还剩几本？', options: ['0本', '7本', '8本'], answer: '0本', explanation: '8×7=56，刚好分完，余数为0。' },
{ id: 'm-a-30', category: 'application', type: 'multiple-choice', text: '从家到学校要走15分钟，早上7:30从家出发，几点到学校？', options: ['7:45', '7:50', '8:00'], answer: '7:45', explanation: '7时30分+15分=7时45分。' },
{ id: 'm-a-31', category: 'application', type: 'multiple-choice', text: '二年级有4个班，每班选9人参加跳绳比赛，一共选多少人？', options: ['36人', '13人', '27人'], answer: '36人', explanation: '求几个几是多少用乘法，4×9=36。' },
{ id: 'm-a-32', category: 'application', type: 'multiple-choice', text: '一根铁丝长40厘米，做一个边长8厘米的正方形框架，还剩多少厘米？', options: ['8厘米', '16厘米', '24厘米'], answer: '8厘米', explanation: '正方形周长=边长×4，8×4=32，40-32=8。' },
{ id: 'm-a-33', category: 'application', type: 'multiple-choice', text: '商店有香蕉25千克，苹果比香蕉多12千克，苹果和香蕉一共多少千克？', options: ['62千克', '37千克', '52千克'], answer: '62千克', explanation: '先算苹果25+12=37，再加香蕉，37+25=62。' },
{ id: 'm-a-34', category: 'application', type: 'multiple-choice', text: '买4本笔记本花20元，每本笔记本多少元？', options: ['5元', '4元', '6元'], answer: '5元', explanation: '归一问题，总价÷数量=单价，20÷4=5。' },
{ id: 'm-a-35', category: 'application', type: 'multiple-choice', text: '排队做操，每行站10人，站了6行，还多3人，做操的一共有多少人？', options: ['63人', '60人', '57人'], answer: '63人', explanation: '先算6行的人数10×6=60，再加多的3人，60+3=63。' },
  // --- 数学思维题 (category: logic) ---
  { id: 'm-l-1', category: 'logic', type: 'multiple-choice', text: '找出与其他项不同的一组数：', options: ['2, 4, 6', '10, 12, 14', '5, 10, 15'], answer: '5, 10, 15', explanation: '有两组都是公差为2的偶数序列，另一组公差为5。' },
  { id: 'm-l-2', category: 'logic', type: 'multiple-choice', text: '找规律：2, 5, 9, 14, ( ), 27', options: ['20', '19', '21'], answer: '20', explanation: '加3，加4，加5，接下来加6：14+6=20。' },
  { id: 'm-l-3', category: 'logic', type: 'multiple-choice', text: '灯亮着，拉7下开关，灯是亮的还是暗的？', options: ['暗的', '亮的', '坏了'], answer: '暗的', explanation: '单数下是相反状态。1下暗，2下亮...7下暗。' },
  { id: 'm-l-4', category: 'logic', type: 'multiple-choice', text: '口袋有红白球各4个，至少摸几个保证有一双同色的？', options: ['3个', '2个', '5个'], answer: '3个', explanation: '最坏情况前两个不同色，第三个一定能配对。' },
  { id: 'm-l-5', category: 'logic', type: 'multiple-choice', text: '小猴爬6米高的大树，每次爬上4米又滑下2米，第几次才能爬上树顶？', options: ['2次', '3次', '4次'], answer: '2次', explanation: '第一次爬4米滑2米（实际高2米），第二次从2米处再爬4米，直接到顶（2+4=6米），不需要再滑下来了。' },
  { id: 'm-l-6', category: 'logic', type: 'multiple-choice', text: '灯不亮，淘气的小狗拉了10次开关，这时候灯亮着吗？', options: ['不亮', '亮', '坏了'], answer: '不亮', explanation: '开关拉2次恢复原状（偶数次不改状态，奇数次改变）。10是偶数，所以还是不亮。' },
  { id: 'm-l-7', category: 'logic', type: 'multiple-choice', text: '一根木头锯成5段，要锯几次？', options: ['4次', '5次', '6次'], answer: '4次', explanation: '锯的次数总是比段数少1。5 - 1 = 4次。' },
  { id: 'm-l-8', category: 'logic', type: 'multiple-choice', text: '把7根短绳连成一根长绳，要打几个结？', options: ['6个', '7个', '8个'], answer: '6个', explanation: '连接处的结总是比绳子数量少1。7 - 1 = 6个。' },
  { id: 'm-l-9', category: 'logic', type: 'multiple-choice', text: '1到50的号码中，数字“1”一共出现了几次？', options: ['15次', '14次', '5次'], answer: '15次', explanation: '个位是1的有5个(1,11,21,31,41)；十位是1的有10个(10-19)。5 + 10 = 15次。' },
  { id: 'm-l-10', category: 'logic', type: 'multiple-choice', text: '鸭妈妈数孩子，从后向前数自己是第6，从前向后数自己是第7，一共有几个孩子？', options: ['11个', '12个', '13个'], answer: '11个', explanation: '队伍总数 = 6 + 7 - 1(鸭妈妈) = 12只。题目问有几个“孩子”，所以 12 - 1 = 11个。' },
  { id: 'm-l-11', category: 'logic', type: 'multiple-choice', text: '停电点燃12支蜡烛，风吹灭了9支。第二天早上还剩几支？', options: ['9支', '3支', '0支'], answer: '9支', explanation: '这是一个脑筋急转弯。没有被吹灭的蜡烛都烧完了，只有被吹灭的9支留了下来。' },
  { id: 'm-l-12', category: 'logic', type: 'multiple-choice', text: '10个小朋友玩老鹰抓小鸡（1人扮老鹰，1人扮母鸡），捉住了5只小鸡，还有几只没被捉住？', options: ['3只', '4只', '5只'], answer: '3只', explanation: '小鸡总数 = 10 - 1(鹰) - 1(母) = 8只。没被捉 = 8 - 5 = 3只。' },
  { id: 'm-l-13', category: 'logic', type: 'multiple-choice', text: '小明一个人走进教室，看见有7个同学在教室，请问现在教室有几个人？', options: ['8个', '7个', '6个'], answer: '8个', explanation: '原来的7个同学 + 走进来的小明 = 8个人。' },
  { id: 'm-l-14', category: 'logic', type: 'multiple-choice', text: '3个男同学与3个女同学进行打球比赛，如果每个男同学都要与每个女同学比赛1次，一共需要比赛几次？', options: ['9次', '6次', '3次'], answer: '9次', explanation: '3个男生，每个人都要打3场，3 × 3 = 9次。' },
  { id: 'm-l-15', category: 'logic', type: 'multiple-choice', text: '小力今年6岁，奶奶说等小力9岁的时候奶奶就55岁了。奶奶今年几岁？', options: ['52岁', '55岁', '49岁'], answer: '52岁', explanation: '小力长了 9 - 6 = 3岁，所以奶奶今年是 55 - 3 = 52岁。' },
  { id: 'm-l-16', category: 'logic', type: 'multiple-choice', text: '找规律：13, 31, 24, 42, 35, 53, ( ), ( )', options: ['46, 64', '45, 54', '46, 65'], answer: '46, 64', explanation: '规律是数字倒过来。接下来应该是46和64。' },
  { id: 'm-l-17', category: 'logic', type: 'multiple-choice', text: '8个男生排成一排，每两个男生之间有一个女生，这一排共有几个学生？', options: ['15个', '16个', '14个'], answer: '15个', explanation: '8个男生之间有7个空隙，所以有7个女生。8 + 7 = 15个。' },
  { id: 'm-l-18', category: 'logic', type: 'multiple-choice', text: '小红用同样的钱可以买3只蛋糕或者4只面包，哪个贵？', options: ['蛋糕', '面包', '一样贵'], answer: '蛋糕', explanation: '同样的钱，买的数量越少，说明单价越贵。' },
  { id: 'm-l-19', category: 'logic', type: 'multiple-choice', text: '口袋有黑袜子和白袜子各三双，杂乱放在一起，至少摸几只才能保证配成一双颜色相同的？', options: ['3只', '2只', '4只'], answer: '3只', explanation: '颜色只有黑和白2种。如果你摸了2只正好一黑一白，第3只不管是什么颜色，都能和前面的一只配对。' },
  { id: 'm-l-20', category: 'logic', type: 'multiple-choice', text: '一本书，小红第一天读1页，以后每天都比前一天多读1页，读到第4天，一共读了几页？', options: ['10页', '4页', '8页'], answer: '10页', explanation: '1 + 2 + 3 + 4 = 10页。' },
  { id: 'm-l-21', category: 'logic', type: 'multiple-choice', text: '一根彩带对折3次后长2厘米，这根彩带原来长多少厘米？', options: ['16厘米', '8厘米', '6厘米'], answer: '16厘米', explanation: '对折1次2段，2次4段，3次8段。8 × 2 = 16厘米。' },
  { id: 'm-l-22', category: 'logic', type: 'multiple-choice', text: '有10块糖，分给5个好朋友，每人2块，小明自己还剩几块？', options: ['0块', '5块', '2块'], answer: '0块', explanation: '5个人 × 2块 = 10块。10 - 10 = 0块，分完了。' },
  { id: 'm-l-23', category: 'logic', type: 'multiple-choice', text: '找规律：1、2、4、7、11、（ ）', options: ['16', '15', '14'], answer: '16', explanation: '每次增加的数分别是1、2、3、4。所以下一个增加5。11 + 5 = 16。' },

  // --- 语文连词成句 (category: sentence) ---
  { id: 'c-s-1', category: 'sentence', type: 'unscramble', text: '我们 / 公园 / 周末 / 常常 / 去 / 玩', answer: '我们周末常常去公园玩', explanation: '时间（周末）通常放在主语后或句首。' },
  { id: 'c-s-2', category: 'sentence', type: 'unscramble', text: '美丽的 / 春天 / 花儿 / 开了 / 公园里', answer: '春天公园里美丽的花儿开了', explanation: '描述“美丽的”修饰花儿。' },
  { id: 'c-s-3', category: 'sentence', type: 'unscramble', text: '老师 / 我们 / 关心 / 非常 / 的 / 成长', answer: '老师非常关心我们的成长', explanation: '关心的是成长。' },
  { id: 'c-s-4', category: 'sentence', type: 'unscramble', text: '小明 / 是 / 爱学习 / 的 / 好孩子 / 一个', answer: '小明是一个爱学习的好孩子', explanation: '“一个”修饰好孩子。' },
  { id: 'c-s-5', category: 'sentence', type: 'unscramble', text: '在 / 小鸟 / 枝头 / 高兴地 / 唱歌', answer: '小鸟在枝头高兴地唱歌', explanation: '主语小鸟在做什么。' },
  { id: 'c-s-6', category: 'sentence', type: 'unscramble', text: '妈妈 / 买了 / 苹果 / 许多 / 新鲜的', answer: '妈妈买了许多新鲜的苹果', explanation: '正确语序是：主语 + 谓语 + 数量形容词修饰的宾语。' },
  { id: 'c-s-7', category: 'sentence', type: 'unscramble', text: '同学们 / 操场上 / 跑步 / 正在 / 快乐地', answer: '同学们正在操场上快乐地跑步', explanation: '动作发生的状态描述。' },
  { id: 'c-s-8', category: 'sentence', type: 'unscramble', text: '这本书 / 我 / 送给 / 是 / 爸爸 / 的', answer: '这本书是爸爸送给我的', explanation: '物品所有权归属描述。' },
  { id: 'c-s-9', category: 'sentence', type: 'unscramble', text: '为什么 / 你 / 今天 / 没来 / 上学 / 呢', answer: '你今天为什么没来上学呢', explanation: '疑问句的正常语序。' },
  { id: 'c-s-10', category: 'sentence', type: 'unscramble', text: '香山的 / 红叶 / 看过 / 你 / 吗', answer: '你看过香山的红叶吗', explanation: '简单疑问句。' },
   { id: 'c-s-11', category: 'sentence', type: 'unscramble', text: '小鸟 / 天空中 / 自由地 / 在 / 飞翔', answer: '小鸟在天空中自由地飞翔', explanation: '主语+地点+状态+谓语。' },
  { id: 'c-s-12', category: 'sentence', type: 'unscramble', text: '多么 / 春天 / 美丽 / 啊', answer: '春天多么美丽啊', explanation: '感叹句语序。' },
  { id: 'c-s-13', category: 'sentence', type: 'unscramble', text: '你 / 去过 / 北京 / 吗', answer: '你去过北京吗', explanation: '疑问句语序。' },
  { id: 'c-s-14', category: 'sentence', type: 'unscramble', text: '妈妈 / 我 / 给 / 一件 / 买了 / 漂亮的 / 裙子', answer: '妈妈给我买了一件漂亮的裙子', explanation: '双宾语结构：给谁买什么。' },
{ id: 'c-s-15', category: 'sentence', type: 'unscramble', text: '荷叶 / 圆圆的 / 绿绿的 / 池塘里', answer: '池塘里荷叶圆圆的绿绿的', explanation: '地点在前，叠词修饰名词放主语后。' },
{ id: 'c-s-16', category: 'sentence', type: 'unscramble', text: '我 / 认真地 / 老师 / 听 / 讲课', answer: '我认真地听老师讲课', explanation: '状语“认真地”修饰谓语，双宾语结构：听谁讲什么。' },
{ id: 'c-s-17', category: 'sentence', type: 'unscramble', text: '秋天 / 一片片 / 树叶 / 从树上 / 落下来', answer: '秋天一片片树叶从树上落下来', explanation: '时间在前，数量词修饰名词放主语前。' },
{ id: 'c-s-18', category: 'sentence', type: 'unscramble', text: '多么 / 可爱 / 这只 / 小白兔 / 啊', answer: '这只小白兔多么可爱啊', explanation: '量词修饰名词放主语前，感叹句核心词放最后。' },
{ id: 'c-s-19', category: 'sentence', type: 'unscramble', text: '弟弟 / 在 / 客厅里 / 开心地 / 搭积木', answer: '弟弟在客厅里开心地搭积木', explanation: '主语+地点+状态+谓语+宾语的基础语序。' },
{ id: 'c-s-20', category: 'sentence', type: 'unscramble', text: '爷爷 / 每天 / 公园 / 去 / 散步', answer: '爷爷每天去公园散步', explanation: '频率副词“每天”放主语后、谓语前。' },
{ id: 'c-s-21', category: 'sentence', type: 'unscramble', text: '彩虹 / 雨后 / 天空中 / 出现了 / 一道', answer: '雨后天空中出现了一道彩虹', explanation: '时间在前，“一道”作为量词修饰彩虹放宾语前。' },
{ id: 'c-s-22', category: 'sentence', type: 'unscramble', text: '你 / 能 / 帮我 / 拿一下 / 水杯 / 吗', answer: '你能帮我拿一下水杯吗', explanation: '能愿动词“能”放谓语前，疑问句语气词放句尾。' },
{ id: 'c-s-23', category: 'sentence', type: 'unscramble', text: '教室里 / 同学们 / 都 / 安静地 / 看书', answer: '教室里同学们都安静地看书', explanation: '范围副词“都”放主语后、状态状语前。' },
{ id: 'c-s-24', category: 'sentence', type: 'unscramble', text: '爸爸 / 给 / 我 / 讲了 / 一个 / 有趣的 / 故事', answer: '爸爸给我讲了一个有趣的故事', explanation: '双宾语结构，形容词+量词修饰宾语放最后。' },
{ id: 'c-s-25', category: 'sentence', type: 'unscramble', text: '雪花 / 冬天 / 慢悠悠地 / 从天上 / 飘下来', answer: '冬天雪花慢悠悠地从天上飘下来', explanation: '状态副词“慢悠悠地”放主语后、地点状语前。' },
{ id: 'c-s-26', category: 'sentence', type: 'unscramble', text: '我们 / 要 / 爱护 / 花草树木 / 身边的', answer: '我们要爱护身边的花草树木', explanation: '能愿动词“要”放谓语前，定语“身边的”修饰宾语。' },
{ id: 'c-s-27', category: 'sentence', type: 'unscramble', text: '夜晚 / 天上的 / 星星 / 一闪一闪的 / 亮着', answer: '夜晚天上的星星一闪一闪的亮着', explanation: '叠词“一闪一闪的”修饰谓语，表动作状态。' },
{ id: 'c-s-28', category: 'sentence', type: 'unscramble', text: '奶奶 / 亲手 / 为我 / 做了 / 一碗 / 香喷喷的 / 面条', answer: '奶奶亲手为我做了一碗香喷喷的面条', explanation: '方式状语“亲手”放主语后，多层定语修饰宾语。' },
{ id: 'c-s-29', category: 'sentence', type: 'unscramble', text: '哪里 / 你在 / 找到 / 这只 / 小鸟 / 的 / 呢', answer: '你在哪里找到这只小鸟的呢', explanation: '疑问词“哪里”放谓语前，疑问句语序梳理。' },
{ id: 'c-s-30', category: 'sentence', type: 'unscramble', text: '春天 / 小燕子 / 从南方 / 飞回来了 / 可爱的', answer: '春天可爱的小燕子从南方飞回来了', explanation: '定语“可爱的”放主语前，表地点的补语放谓语前。' },
{ id: 'c-s-31', category: 'sentence', type: 'unscramble', text: '我 / 和 / 小伙伴 / 一起 / 去 / 郊外 / 放风筝', answer: '我和小伙伴一起去郊外放风筝', explanation: '并列主语用“和”连接，“一起”表伴随放谓语前。' },
{ id: 'c-s-32', category: 'sentence', type: 'unscramble', text: '多么 / 清澈 / 小河里的 / 河水 / 啊', answer: '小河里的河水多么清澈啊', explanation: '定语修饰名词放主语前，感叹句核心形容词放中间。' },
{ id: 'c-s-33', category: 'sentence', type: 'unscramble', text: '老师 / 告诉 / 我们 / 要 / 认真 / 学习', answer: '老师告诉我们要认真学习', explanation: '双宾语结构，“要”引导的祈使内容放句尾。' },
{ id: 'c-s-34', category: 'sentence', type: 'unscramble', text: '早晨 / 阳光 / 温暖的 / 照进 / 了 / 我的房间', answer: '早晨温暖的阳光照进了我的房间', explanation: '形容词定语放名词前，“了”表动作完成放谓语后。' },
{ id: 'c-s-35', category: 'sentence', type: 'unscramble', text: '你 / 知道 / 这朵花 / 叫什么 / 名字 / 吗', answer: '你知道这朵花叫什么名字吗', explanation: '主谓宾结构中嵌套疑问短语，语气词放句尾。' },
  // --- 语文选词填空 (category: word) ---
  // 新增复杂多空题目
{ id: 'c-w-complex-1', category: 'word', type: 'fill-in-the-blank', text: '今天妈妈要去（ ）厂上班，周末我们（ ）去（ ）园玩。', options: ['工', '公', '在', '再'], answer: '工再公', explanation: '“工厂”用工，“再去”用再，“公园”用公。' },
{ id: 'c-w-complex-2', category: 'word', type: 'fill-in-the-blank', text: '我（ ）家写（ ）业。', options: ['在', '再', '做', '作'], answer: '在作', explanation: '“在家”表示地点用在，“作业”名词用作。' },
{ id: 'c-w-complex-3', category: 'word', type: 'fill-in-the-blank', text: '我们（ ）在（ ）树下玩游戏。', options: ['正', '真', '大', '太'], answer: '正大', explanation: '“正在”表示进行，“大树”形容树大。' },
{ id: 'c-w-complex-4', category: 'word', type: 'fill-in-the-blank', text: '这个（ ）皮球花了五（ ）钱，滚到了（ ）园的角落。', options: ['圆', '元', '公', '工'], answer: '圆元公', explanation: '“圆”表形状，“元”是人民币单位，“公园”是固定搭配用公。' },
{ id: 'c-w-complex-5', category: 'word', type: 'fill-in-the-blank', text: '我（ ）门口等你，你（ ）把那道题（ ）完。', options: ['在', '再', '做', '作'], answer: '在再做', explanation: '“在”表位置，“再”表重复动作，“做题”表从事活动用做。' },
{ id: 'c-w-complex-6', category: 'word', type: 'fill-in-the-blank', text: '（ ）阳下，（ ）空中飘着（ ）云，（ ）树旁有小朋友在玩。', options: ['太', '天', '白', '大'], answer: '太天白大', explanation: '“太阳”“天空”是固定搭配，“白云”表颜色，“大树”形容体积用大。' },
{ id: 'c-w-complex-7', category: 'word', type: 'fill-in-the-blank', text: '我（ ）有一（ ）笔，笔杆上有一（ ）嫩绿的小花，我（ ）道这是妈妈送的。', options: ['只', '支', '枝', '知'], answer: '只支枝知', explanation: '“只”表数量少，“支”是笔的量词，“枝”修饰枝条类事物，“知道”是固定搭配。' },
{ id: 'c-w-complex-8', category: 'word', type: 'fill-in-the-blank', text: '小鱼（ ）河（ ）游，小鸟（ ）树（ ）唱，我们（ ）草地上笑。', options: ['在', '在','里', '上', '下'], answer: '在里在上在', explanation: '“在”表位置，“河里”“树上”“草地上”是方位固定搭配。' },
{ id: 'c-w-complex-9', category: 'word', type: 'fill-in-the-blank', text: '我用（ ）看风景，用（ ）听歌声，用（ ）写字，用（ ）跑步。', options: ['目', '耳', '手', '足'], answer: '目耳手足', explanation: '目是眼睛管看，耳是耳朵管听，手管写字，足是脚管跑步。' },
{ id: 'c-w-complex-10', category: 'word', type: 'fill-in-the-blank', text: '我（ ）见他拿（ ）一（ ）书，正坐在（ ）石凳上读。', options: ['见', '着', '本', '小'], answer: '见着本小', explanation: '“看见”是固定搭配，“着”表动作持续，“本”是书的量词，“小”修饰石凳。' },
{ id: 'c-w-complex-11', category: 'word', type: 'fill-in-the-blank', text: '农民伯伯（ ）（ ）里种瓜，瓜熟了吃起来真（ ）。', options: ['在', '田', '甜', '天'], answer: '在田甜', explanation: '“在”表位置，“田里”是种瓜的地方，“甜”形容瓜的味道。' },
{ id: 'c-w-complex-12', category: 'word', type: 'fill-in-the-blank', text: '我的好（ ）友，（ ）（ ）和我一起（ ）书、做（ ）业。', options: ['朋', '总', '是', '看', '作'], answer: '朋总是看作', explanation: '“朋友”是固定搭配，“总是”表一直，“看书”“作业”是固定搭配。' },
{ id: 'c-w-complex-13', category: 'word', type: 'fill-in-the-blank', text: '（ ）在的天气真（ ）好，我们（ ）去郊外看（ ）丽的小花。', options: ['现', '真', '再', '美'], answer: '现真再美', explanation: '“现在”表当下，“真好”表程度，“再”表动作重复，“美丽”修饰小花。' },
{ id: 'c-w-complex-14', category: 'word', type: 'fill-in-the-blank', text: '他（ ）在画一（ ）（ ）的太阳，画完（ ）给老师看。', options: ['正', '个', '红', '拿'], answer: '正个红拿', explanation: '“正在”表动作进行，“个”是太阳的量词，“红”表颜色，“拿给”是动作搭配。' },
{ id: 'c-w-complex-15', category: 'word', type: 'fill-in-the-blank', text: '一（ ）小鸟（ ）（ ）头，（ ）着翅膀飞向（ ）空。', options: ['只', '抬', '起', '展', '天'], answer: '只抬起展天', explanation: '“只”是小鸟的量词，“抬起头”“展开翅膀”是动作搭配，“天空”是固定词语。' },
{ id: 'c-w-complex-16', category: 'word', type: 'fill-in-the-blank', text: '我（ ）家门口等你，明天我们（ ）去公园玩。', options: ['在', '再', '有', '又'], answer: '在再', explanation: '“在”表位置，“再”表将来的重复动作。' },
{ id: 'c-w-complex-17', category: 'word', type: 'fill-in-the-blank', text: '我（ ）了新玩具，草地上（ ）来了几只小鸟。', options: ['在', '再', '有', '又'], answer: '有又', explanation: '“有”表示拥有，“又”表动作的追加重复。' },
{ id: 'c-w-complex-19', category: 'word', type: 'fill-in-the-blank', text: '我的（ ）发有点长了，我用（ ）写出了漂亮的字。', options: ['头', '手', '耳', '目'], answer: '头手', explanation: '“头发”是固定词语，“手”是写字的身体部位。' },
{ id: 'c-w-complex-20', category: 'word', type: 'fill-in-the-blank', text: '（ ）阳高照的日子，我有一个（ ）大的苹果。', options: ['太', '大', '天', '白'], answer: '太大', explanation: '“太阳”是固定词语，“大”形容物体体积。' },
{ id: 'c-w-complex-21', category: 'word', type: 'fill-in-the-blank', text: '我（ ）道他会来，我（ ）有一支铅笔送给他。', options: ['知', '只', '支', '枝'], answer: '知只', explanation: '“知道”是固定词语，“只”表示数量少。' },
{ id: 'c-w-complex-22', category: 'word', type: 'fill-in-the-blank', text: '他是我的好（ ）友，（ ）天我们一起去郊游', options: ['朋', '棚', '彭', '明'], answer: '朋明', explanation: '“朋友”是固定词语，“明天”表将来的时间。' },
{ id: 'c-w-complex-23', category: 'word', type: 'fill-in-the-blank', text: '农民伯伯在（ ）里种菜，西瓜吃起来真（ ）。', options: ['田', '天', '甜', '电'], answer: '田甜', explanation: '“田里”是种菜的地方，“甜”形容西瓜的味道。' },
{ id: 'c-w-complex-24', category: 'word', type: 'fill-in-the-blank', text: '我每天都要（ ）书，还看（ ）了许多有趣的故事。', options: ['看', '着', '见', '听'], answer: '看见', explanation: '“看书”是固定搭配，“看见”表示看到、发觉。' },
{ id: 'c-w-complex-25', category: 'word', type: 'fill-in-the-blank', text: '我看（ ）了一只小鸟，它扇（ ）翅膀飞向蓝天。', options: ['看', '着', '见', '听'], answer: '见着', explanation: '“看见”表发现，“着”表动作的持续状态。' },
{ id: 'c-w-complex-26', category: 'word', type: 'fill-in-the-blank', text: '（ ）天我（ ）学了，（ ）天就可以和同学一起做游（ ）。', options: ['今', '明', '上', '戏'], answer: '今上明戏', explanation: '“今天”表当下，“上学”是固定搭配，“明天”表将来，“游戏”是固定词语。' },
{ id: 'c-w-complex-27', category: 'word', type: 'fill-in-the-blank', text: '一（ ）小雨落下来，（ ）在窗（ ）上，打（ ）了门前的小花。', options: ['场', '打', '户', '湿'], answer: '场打户湿', explanation: '“场”是雨的量词，“打在”表动作，“窗户”是固定搭配，“打湿”表状态。' },
{ id: 'c-w-complex-28', category: 'word', type: 'fill-in-the-blank', text: '我（ ）手把书（ ）好，放（ ）了书（ ）里。', options: ['用', '合', '进', '包'], answer: '用合进包', explanation: '“用手”表动作工具，“合好”表整理动作，“放进”表方位变化，“书包”是固定搭配。' },
{ id: 'c-w-complex-29', category: 'word', type: 'fill-in-the-blank', text: '（ ）光洒（ ）田野，麦（ ）摇（ ），像在点头问好。', options: ['阳', '满', '苗', '晃'], answer: '阳满苗晃', explanation: '“阳光”是固定搭配，“洒满”表覆盖，“麦苗”是固定词语，“摇晃”表动作。' },
{ id: 'c-w-complex-30', category: 'word', type: 'fill-in-the-blank', text: '他（ ）快地跑（ ）教室，（ ）上了门，（ ）始认真听课。', options: ['飞', '进', '关', '开'], answer: '飞进关开', explanation: '“飞快”表速度，“跑进”表方位，“关上”表动作，“开始”是固定搭配。' },
{ id: 'c-w-complex-31', category: 'word', type: 'fill-in-the-blank', text: '一（ ）小船飘在（ ）面上，船（ ）坐（ ）一位老爷爷。', options: ['条', '水', '头', '着'], answer: '条水头着', explanation: '“条”是船的量词，“水面”是固定搭配，“船头”表位置，“坐着”表状态。' },
{ id: 'c-w-complex-32', category: 'word', type: 'fill-in-the-blank', text: '妈妈（ ）来一碗（ ）汤，（ ）在桌（ ）上，让我趁热喝。', options: ['端', '热', '放', '子'], answer: '端热放子', explanation: '“端来”表动作，“热汤”表属性，“放在”表位置，“桌子”是固定搭配。' },
{ id: 'c-w-complex-33', category: 'word', type: 'fill-in-the-blank', text: '（ ）朵鲜花开在（ ）边，（ ）风一吹，就飘出（ ）香。', options: ['几', '河', '微', '清'], answer: '几河微清', explanation: '“几朵”表数量，“河边”表位置，“微风”是固定搭配，“清香”表气味。' },
{ id: 'c-w-complex-34', category: 'word', type: 'fill-in-the-blank', text: '我（ ）完作业，（ ）上球鞋，（ ）着球，去（ ）外和伙伴玩。', options: ['做', '穿', '拿', '门'], answer: '做穿拿门', explanation: '“做作业”是固定搭配，“穿上”表动作，“拿着”表状态，“门外”表方位。' },
{ id: 'c-w-complex-35', category: 'word', type: 'fill-in-the-blank', text: '夜（ ）的天（ ）有许（ ）星（ ），一闪一闪的。', options: ['晚', '空', '多', '星'], answer: '晚空多星', explanation: '“夜晚”表时间，“天空”是固定搭配，“许多”表数量，“星星”是叠词固定词语。' },
{ id: 'c-w-complex-36', category: 'word', type: 'fill-in-the-blank', text: '老（ ）带（ ）我们，去（ ）外看（ ）丽的风景。', options: ['师', '着', '校', '美'], answer: '师着校美', explanation: '“老师”是固定搭配，“带着”表伴随，“校外”表方位，“美丽”表修饰。' },
{ id: 'c-w-complex-37', category: 'word', type: 'fill-in-the-blank', text: '我（ ）见（ ）声雷响，（ ）点越下越（ ）。', options: ['听', '几', '雨', '大'], answer: '听几雨大', explanation: '“听见”是固定搭配，“几声”表数量，“雨点”是固定词语，“大”表程度。' },
{ id: 'c-w-complex-38', category: 'word', type: 'fill-in-the-blank', text: '一（ ）树叶从树（ ）落（ ），（ ）到了我的肩头。', options: ['片', '上', '下', '飘'], answer: '片上下飘', explanation: '“片”是树叶的量词，“树上”表位置，“落下”表动作，“飘在”表状态。' },
{ id: 'c-w-complex-39', category: 'word', type: 'fill-in-the-blank', text: '妹妹（ ）着糖，（ ）着小（ ），（ ）快地跑向妈妈。', options: ['含', '牵', '手', '飞'], answer: '含牵手飞', explanation: '“含着”表状态，“牵着”表动作，“小手”表身体部位，“飞快”表速度。' },
{ id: 'c-w-complex-40', category: 'word', type: 'fill-in-the-blank', text: '（ ）节到了，我（ ）上新衣，（ ）着灯笼，和家人一（ ）过节。', options: ['春', '穿', '提', '起'], answer: '春穿提起', explanation: '“春节”是固定节日，“穿上”表动作，“提着”表状态，“一起”表伴随。' },
{ id: 'c-w-complex-41', category: 'word', type: 'fill-in-the-blank', text: '书（ ）里有许（ ）书，同（ ）们正（ ）静地看书。', options: ['房', '多', '学', '安'], answer: '房多学安', explanation: '“书房”是固定搭配，“许多”表数量，“同学”是固定词语，“安静”表状态。' },
{ id: 'c-w-complex-42', category: 'word', type: 'fill-in-the-blank', text: '我（ ）心画了一（ ）画，（ ）上颜色，（ ）给老师看。', options: ['用', '幅', '涂', '拿'], answer: '用幅涂拿', explanation: '“用心”表态度，“幅”是画的量词，“涂上”表动作，“拿给”表对象。' },
{ id: 'c-w-complex-43', category: 'word', type: 'fill-in-the-blank', text: '（ ）晨，我（ ）到公（ ）里，看（ ）了许多晨练的人。', options: ['清', '走', '园', '见'], answer: '清走园见', explanation: '“清晨”表时间，“走到”表动作，“公园”是固定搭配，“看见”是固定词语。' },
{ id: 'c-w-complex-45', category: 'word', type: 'fill-in-the-blank', text: '饭（ ）了，妈妈（ ）我洗（ ），然（ ）一起吃饭。', options: ['熟', '叫', '手', '后'], answer: '熟叫手后', explanation: '“饭熟了”表状态，“叫我”表动作，“洗手”是固定搭配，“然后”表顺序。' },
{ id: 'c-w-complex-46', category: 'word', type: 'fill-in-the-blank', text: '这（ ）歌很（ ）听，我（ ）着旋律，轻（ ）地跟着唱。', options: ['首', '好', '跟', '轻'], answer: '首好跟轻', explanation: '“首”是歌的量词，“好听”表评价，“跟着”表伴随，“轻轻地”表状态。' },
{ id: 'c-w-complex-47', category: 'word', type: 'fill-in-the-blank', text: '（ ）雪从天（ ）飘（ ），盖（ ）了地上的小草。', options: ['小', '上', '下', '住'], answer: '小上下住', explanation: '“小雪”表天气，“天上”表位置，“飘下”表动作，“盖住”表状态。' },
{ id: 'c-w-complex-48', category: 'word', type: 'fill-in-the-blank', text: '我（ ）了一（ ）话，写在纸（ ）上，（ ）给了好朋友。', options: ['说', '句', '片', '递'], answer: '说句片递', explanation: '“说了”表动作，“句”是话的量词，“纸片”表载体，“递给”表动作。' },
{ id: 'c-w-complex-49', category: 'word', type: 'fill-in-the-blank', text: '（ ）车开（ ）了，我（ ）手和站在（ ）边的奶奶再见。', options: ['火', '走', '挥', '路'], answer: '火走挥路', explanation: '“火车”是固定搭配，“开走了”表状态，“挥手”是固定动作，“路边”表位置。' },
{ id: 'c-w-complex-50', category: 'word', type: 'fill-in-the-blank', text: '天（ ）了，我（ ）起灯，找（ ）了藏在（ ）后的玩具。', options: ['黑', '开', '到', '门'], answer: '黑开到门', explanation: '“天黑了”表状态，“开起”表动作，“找到”是固定搭配，“门后”表位置。' },
{ id: 'c-w-complex-51', category: 'word', type: 'fill-in-the-blank', text: '妹妹跑（ ）很快，手里拿着飘落（ ）鲜花。', options: ['地', '得', '的', '也'], answer: '得的', explanation: '“地”用在动词前，“得”用在动词后表程度，“的”用在名词前作定语。' },
{ id: 'c-w-complex-53', category: 'word', type: 'fill-in-the-blank', text: '小鸟欢快（ ）唱着歌，飞（ ）了远方。', options: ['地', '的', '向', '象'], answer: '地向', explanation: '“地”修饰动词“唱”；“的”修饰名词“歌”；“向”表方向，“象”是动物，此处用向。' },
{ id: 'c-w-complex-55', category: 'word', type: 'fill-in-the-blank', text: '温和（ ）春风轻轻（ ）吹着，小草绿（ ）可爱。', options: ['的', '地', '得', '很'], answer: '的地得', explanation: '“的”修饰名词“春风”；“地”修饰动词“吹”；“得”用在形容词后表程度。' },
{ id: 'c-w-complex-56', category: 'word', type: 'fill-in-the-blank', text: '明亮的（ ）光，照（ ）了小路。', options: ['dēng', 'dēn', '亮', '量', '的'], answer: 'dēng亮', explanation: '“灯”是后鼻音dēng；“的”修饰名词“光”；“照亮”是固定搭配，“量”为数量，此处用亮。' },
{ id: 'c-w-complex-57', category: 'word', type: 'fill-in-the-blank', text: '故事讲（ ）精彩，大家听（ ）入迷。', options: ['的', '地', '得', '都'], answer: '得得', explanation: '“的”修饰名词“故事”；“得”分别用在动词“讲”、“听”后，表动作的程度。' },
{ id: 'c-w-complex-58', category: 'word', type: 'fill-in-the-blank', text: '家乡的（ ）色，记（ ）了我的心里。', options: ['jǐng', 'jǐn', '的', '在'], answer: 'jǐng在', explanation: '“景”是后鼻音jǐng，表景色；“的”修饰名词“色”；“在”表位置，“记在心里”是固定搭配。' },
{ id: 'c-w-complex-59', category: 'word', type: 'fill-in-the-blank', text: '妹妹追蝴蝶，跑（ ）气喘吁吁，摔（ ）坐在地上。', options: ['地', '得', '的', '倒'], answer: '得倒', explanation: '“地”修饰动词“追”；“得”用在动词后表程度；“摔倒”是固定动作，表意外跌倒。' },
{ id: 'c-w-complex-62', category: 'word', type: 'fill-in-the-blank', text: '我选一（ ）书，读（ ）津津有味。', options: ['běn', 'bēn', '的', '得'], answer: 'běn得', explanation: '“本”是前鼻音běn，表量词；“的”修饰名词“书”；“得”用在动词“读”后，表阅读的状态。' },
{ id: 'c-w-complex-64', category: 'word', type: 'fill-in-the-blank', text: '（ ）筝，飞（ ）了高高的天空。', options: ['fēng', 'fēn', '的', '向'], answer: 'fēng向', explanation: '“风”是后鼻音fēng；“的”修饰名词“筝”；“向”表方向，“飞向天空”是固定搭配。' },
{ id: 'c-w-complex-65', category: 'word', type: 'fill-in-the-blank', text: '清晨（ ）阳光轻柔（ ）洒下，照（ ）大地暖洋洋。', options: ['的', '地', '得', '遍'], answer: '的地得', explanation: '“的”修饰名词“阳光”；“地”修饰动词“洒”；“得”用在动词后，引出动作的结果。' },
{ id: 'c-w-complex-67', category: 'word', type: 'fill-in-the-blank', text: '小朋友快乐（ ）做游戏，玩（ ）开心，笑（ ）响亮。', options: ['地', '的', '得', '声'], answer: '地得声', explanation: '“地”修饰动词“做”；两个“得”分别用在“玩”、“笑”后，表动作的情绪和声音程度。' },
{ id: 'c-w-complex-68', category: 'word', type: 'fill-in-the-blank', text: '悦耳的（ ）音，传（ ）了教室的每个角落。', options: ['shēng', 'shēn', '的', '到'], answer: 'shēng到', explanation: '“声”是后鼻音shēng，表声音；“的”修饰名词“音”；“传到”是固定搭配，表传递的范围。' },
{ id: 'c-w-complex-70', category: 'word', type: 'fill-in-the-blank', text: '这个小（ ）孩，跑（ ）比风还快。', options: ['nán', 'náng', '的', '得'], answer: 'nán得', explanation: '“男”是前鼻音nán，表性别；“的”修饰名词“孩”；“得”用在动词“跑”后，表跑的速度程度。' },
{ id: 'c-w-complex-71', category: 'word', type: 'fill-in-the-blank', text: '爷爷仔细（ ）浇花，浇（ ）仔细，花长（ ）茂盛。', options: ['地', '的', '得', '很'], answer: '地得得', explanation: '“地”修饰动词“浇”；两个“得”分别表“浇”的态度和“长”的状态，均用在动词后。' },
{ id: 'c-w-complex-72', category: 'word', type: 'fill-in-the-blank', text: '两人（ ）开，走（ ）了不同的方向。', options: ['fēn', 'fēng', '像', '向'], answer: 'fēn向', explanation: '“分”是前鼻音fēn，表动作；“的”修饰名词“开”（此处为名词化）；“向”表方向，“走向方向”是固定搭配。' },
{ id: 'c-w-complex-73', category: 'word', type: 'fill-in-the-blank', text: '响亮（ ）歌声久久（ ）回荡，唱（ ）大家热泪盈眶。', options: ['的', '地', '得', '响'], answer: '的地得', explanation: '“的”修饰名词“歌声”；“地”修饰动词“回荡”；“得”用在动词后，引出歌声带来的效果。' },
{ id: 'c-w-complex-76', category: 'word', type: 'fill-in-the-blank', text: '我（ ）家，（ ）见窗外（ ）来了一只小鸟。', options: ['zài', 'zhài', '看', '飞'], answer: 'zài看飞', explanation: '“在”读zài，表地点；“看见”是固定搭配，此处选“看”；“落了”表小鸟停留的动作。' },
{ id: 'c-w-complex-77', category: 'word', type: 'fill-in-the-blank', text: '选（ ），用来画（ ），比谁画得好。', options: ['bǐ', 'bì', '笔', '画'], answer: 'bǐ画', explanation: '“比”读bǐ，表比较；“笔”是绘画工具，固定搭配“用笔”；“画画”是固定动作。' },
{ id: 'c-w-complex-78', category: 'word', type: 'fill-in-the-blank', text: '风（ ）过，（ ）叶飘（ ），像蝴蝶飞舞。', options: ['chuī', 'cuī', '树', '下'], answer: 'chuī树下', explanation: '“吹”是翘舌音chuī，表动作；“树叶”是固定词语；“飘下”表方位动作，符合语境。' },
{ id: 'c-w-complex-79', category: 'word', type: 'fill-in-the-blank', text: '他（ ）快（ ）跑，跑（ ）了操场的尽头。', options: ['飞', '地', '到', '的'], answer: '飞地到', explanation: '“飞快”是固定搭配，表速度；“地”用在副词后修饰动词“跑”；“到了”表动作的终点。' },
{ id: 'c-w-complex-80', category: 'word', type: 'fill-in-the-blank', text: '她（ ）了一件（ ）衫在衣架上。', options: ['guā', 'guà', '依', '衣'], answer: 'guà衣', explanation: '“挂”读guà，表动作；“挂了”是动作表达；“衣衫”是固定词语，指衣服。' },
{ id: 'c-w-complex-81', category: 'word', type: 'fill-in-the-blank', text: '太阳（ ）起，（ ）红了东边的天空。', options: ['shēng', 'shēn', '太', '染'], answer: 'shēng染', explanation: '“升”是后鼻音shēng，表动作；“太阳”是固定词语，选“太”；“染红”表颜色变化，符合语境。' },
{ id: 'c-w-complex-82', category: 'word', type: 'fill-in-the-blank', text: '我（ ）了作业，（ ）上书包，（ ）往学校走去。', options: ['做', '背', '向', '象'], answer: '做背向', explanation: '“做作业”是固定搭配；“背上书包”是日常动作；“向”表方向，“向往”此处为“朝着”，“象”是动物，不用。' },
{ id: 'c-w-complex-83', category: 'word', type: 'fill-in-the-blank', text: '我（ ）出家门，（ ）见路边的小花。', options: ['zǒu', 'zhǒu', '看'], answer: 'zǒu看', explanation: '“走”是平舌音zǒu，表动作；“走出家门”是固定搭配；“看见”是固定词语，选“看”。' },
{ id: 'c-w-complex-84', category: 'word', type: 'fill-in-the-blank', text: '（ ）雨了，雨水打（ ）了窗（ ），也打湿了小草。', options: ['xià', 'xà', '到', '户'], answer: 'xià到户', explanation: '“下”读xià，表动作；“打在”是固定搭配，表动作落点；“窗户”是固定词语，选“户”。' },
{ id: 'c-w-complex-85', category: 'word', type: 'fill-in-the-blank', text: '妈妈（ ）来水果，（ ）给我一（ ）苹果，让我慢慢吃。', options: ['端', '递', '个', '棵'], answer: '端递个', explanation: '“端来”表拿取动作；“递给”表传递动作；“个”是水果的量词，“棵”修饰植物，不用。' },
{ id: 'c-w-complex-86', category: 'word', type: 'fill-in-the-blank', text: '我（ ）歌（ ）曲，心情格外好。', options: ['tīng', 'tīn', '唱'], answer: 'tīng唱', explanation: '“听”是后鼻音tīng，表动作；“听歌”是固定搭配；“唱曲”即唱歌，符合语境。' },
{ id: 'c-w-complex-87', category: 'word', type: 'fill-in-the-blank', text: '（ ）们在操场，（ ）着球，玩（ ）十分开心。', options: ['我', '拍', '得', '的'], answer: '我拍得', explanation: '“我们”是人称代词，选“我”；“拍着球”是固定动作；“得”用在动词后表程度，“玩得开心”是固定用法。' },
{ id: 'c-w-complex-88', category: 'word', type: 'fill-in-the-blank', text: '（ ）完书，（ ）懂了里面的故事。', options: ['kàn', 'kǎn', '读'], answer: 'kàn读', explanation: '“看”读kàn，表动作；“看着书”表持续状态；“读懂”是固定搭配，表理解内容。' },
{ id: 'c-w-complex-89', category: 'word', type: 'fill-in-the-blank', text: '小（ ）飞（ ）了天空，（ ）过了白云。', options: ['niǎo', 'niáo', '向', '穿'], answer: 'niǎo向穿', explanation: '“鸟”读niǎo，表动物；“小鸟”是固定词语；“穿过”表从中间经过，符合小鸟飞的语境。' },
{ id: 'c-w-complex-90', category: 'word', type: 'fill-in-the-blank', text: '我（ ）了一杯水，（ ）到嘴边，（ ）了一口真甜。', options: ['倒', '端', '喝', '渴'], answer: '倒端喝', explanation: '“倒水”是固定动作；“端到嘴边”表拿取的方位；“喝”是动作，“渴”是感觉，此处用“喝”。' },
{ id: 'c-w-complex-91', category: 'word', type: 'fill-in-the-blank', text: '（ ）现了一（ ）小花，开在石头旁。', options: ['fā', 'fà', '发', '朵'], answer: 'fā朵', explanation: '“发”表发现时读fā，平舌音；“发现”是固定词语；“朵”是花的量词，固定搭配。' },
{ id: 'c-w-complex-92', category: 'word', type: 'fill-in-the-blank', text: '天（ ）了，我（ ）起灯光，（ ）亮了整个房间。', options: ['黑', '开', '照', '找'], answer: '黑开照', explanation: '“天黑了”是固定表述；“开起灯光”是日常动作；“照亮”表光线的效果，“找”是寻找，不用。' },
{ id: 'c-w-complex-93', category: 'word', type: 'fill-in-the-blank', text: '（ ）下种子，盼它（ ）出小苗。', options: ['zhòng', 'zhǒng', '长'], answer: 'zhòng长', explanation: '“种”表种植时读zhòng，四声；“种下”是固定动作；“长出”表生长，符合语境。' },
{ id: 'c-w-complex-94', category: 'word', type: 'fill-in-the-blank', text: '老师（ ）我们，（ ）真听讲，（ ）得更多知识。', options: ['教', '认', '学', '习'], answer: '教认学', explanation: '“教我们”是师生搭配；“认真听讲”是固定搭配，“认”表态度；“学得知识”是固定表述，表获取。' },
  // 原有题目适配新格式（单空题目，answer为单字字符串，options需足够干扰项）
  { id: 'c-w-5', category: 'word', type: 'fill-in-the-blank', text: '我（ ）家门口等你。', options: ['在', '再', '有', '又'], answer: '在', explanation: '表示处于某个位置，用“在”。' },
   ];
